baseURL = "https://2xiao.github.io/blog"
languageCode = "zh-cn"
title = "äºŒå°ã®åšå®¢"
theme = "github-style"
googleAnalytics = ""
copyright = "<a href='https://github.com/2xiao'>2xiao</a> ã® blog"
pygmentsCodeFences = true
pygmentsUseClasses = true
publishDir = "../docs"

[params]
  author = "äºŒå°"
  github = "2xiao"
  description = "ğŸˆ I have a cat & a boyfriend."
  utterances = "2xiao/blog"
  rss = false
  location = "Beijing,China"
  lastmod = true

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]
